name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      run-id:
        description: 'Workflow run id'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    # https://github.com/pypa/gh-action-pypi-publish?tab=readme-ov-file#trusted-publishing
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/fpylll

    steps:

      - uses: actions/download-artifact@v4
        with:
          pattern: "dist"
          path: dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.inputs.run-id }}

      - uses: actions/download-artifact@v4
        with:
          pattern: "*-wheels"
          path: dist
          merge-multiple: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.inputs.run-id }}

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          skip-existing: true
          verbose: true
